name: seal_scanner
description: "A new Flutter project."
publish_to: "none" # This prevents accidental publishing to pub.dev.

version: 1.1.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  shared_preferences: ^2.0.15  # Ensure you specify the version to avoid issues.
  cupertino_icons: ^1.0.6
  image: ^3.0.1
  image_picker: 
  google_mlkit_text_recognition: 
  mqtt_client: 
  photo_view: 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # assets:
  #   - assets/
  #   - assets/images/
  #   - assets/fonts/
  # If you have custom fonts, uncomment and specify them here:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
